version: "3.8"
services:
  db:
    image: mysql
    container_name: hubdb
    environment:
      MYSQL_DATABASE: studenthub
      MYSQL_USER: new_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - app-net
  web:
    container_name: hubweb
    build: .
    environment:
      MYSQL_DATABASE: studenthub
      MYSQL_USER: new_user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
